# Generated by Django 5.2.7 on 2025-10-24 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('citizenship', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='coach_photos/')),
                ('club', models.CharField(max_length=20)),
                ('license', models.CharField(max_length=50)),
                ('preffered_formation', models.CharField(help_text='Contoh: 4-3-3 Attacking', max_length=100)),
                ('average_term_as_coach', models.FloatField(help_text='Dalam tahun, contoh: 3.5')),
                ('description', models.TextField(help_text='Bisa diisi dengan klub terakhir, gaya melatih, dll.')),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoachRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('citizenship', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='coach_requests/')),
                ('club', models.CharField(max_length=20)),
                ('license', models.CharField(max_length=50)),
                ('preffered_formation', models.CharField(max_length=100)),
                ('average_term_as_coach', models.FloatField()),
                ('description', models.TextField()),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Catatan untuk sesi ini (opsional)', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
